# I learned how to take user input and make variables. I made a code to ask some basic questions.
MyName = input("What's your name?: ")
MyAge = input("How old are you?: ")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit? ")
print("OF COURSE YOU DO!")
print("ok")
print("So, you are")
print(MyName)
print("and are the ripe old age of")
print(MyAge)
print("and clearly think that Replit is")
print(replit)
myGrandma = input("How's your Grandma doing? ")
print(myGrandma)
